[package]
name = "fwd"
version = "0.9.2"
authors = ["John Doty <john@d0ty.me>"]
edition = "2021"
license = "MIT"
description = "Automatically forward ports to a remote server"
readme = "README.md"
documentation = "https://github.com/DeCarabas/fwd"
homepage = "https://github.com/DeCarabas/fwd"
repository = "https://github.com/DeCarabas/fwd"

[[bin]]
name = "fwd-browse"
test = false
bench = false

[dependencies]
anyhow = "1.0"
bytes = "1"
copypasta = "0.10.1"
crossterm = { version = "0.28.1", features = ["event-stream"] }
directories-next = "2"
env_logger = { version = "0.11.5", default-features = false }
indoc = "1"
log = { version = "0.4", features = ["std"] }
open = "3"
rand = "0.8.5"
ratatui = "0.28.0"
thiserror = "1.0"
tokio = { version = "1", features = ["io-std", "io-util", "macros", "net", "process", "rt", "rt-multi-thread", "fs"] }
tokio-stream = "0.1"
toml = "0.5"


[dev-dependencies]
assert_matches = "1"
pretty_assertions = "1"
tempfile = "3"

[target.'cfg(target_os="linux")'.dependencies]
procfs = "0.14.1"

[target.'cfg(target_family="unix")'.dependencies]
libc = "0.2.155"

[package.metadata.deb]
section = "net"
depends = [] # No auto deps?
assets = [
  ["target/release/fwd", "usr/bin/", "755"],
  ["target/release/fwd-browse", "usr/bin/", "755"],
  ["LICENSE", "usr/share/doc/fwd/", "644"],
  ["README.md", "usr/share/doc/fwd/README", "644"],
  # The man page is automatically generated by fwd's build process. See
  # release.py for details.
  ["target/release/fwd.1", "usr/share/man/man1/fwd.1", "644"],
]
extended-description = """\
fwd enumerates the listening ports the remote server and automatically listens
for connections on the same ports on the local machine. When fwd receives a
connection on the local machine, it automatically forwards that connection to
the remote machine.
"""
